            - name: Deploy to Neocities
  # You may pin to the exact commit or the version.
  # uses: bcomnes/deploy-to-neocities@60adbf96af7b57e13a551e35ff57b74142f9655f
  uses: bcomnes/deploy-to-neocities@v3.0.2
  with:
    # Neocities API key for site to deploy to
    api_key: 
    # Local folder to deploy to neocities
    dist_dir: # default is public
    # Set to true if you are a Neocities supporter to bypass file type upload restrictions
    neocities_supporter: # default is false
    # Delete orphaned files on neocities that don't exist in distDir
    cleanup: # default is false
    # Set to true if you want to print deploy preview stats prior to deploying.
    preview_before_deploy: # optional, default is true
    # A glob string that prevents matched files from ever being deleted.
    protected_files: # optional
    # Neocities API key for site to deploy to
    api_token: # optional
          
